import Sidebar from "@/components/page/dashboard/Sidebar";
import FooterBottom from "@/components/shared/FooterButtom";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard| Portfolio",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Sidebar>{children}</Sidebar>
      <FooterBottom />
    </>
  );
}
